version: "3.8"

services: 
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Connect to Docker daemon
  
  mongodb:
    image: mongo
    container_name: app-mongodb
    restart: always
    ports:
      - "27018:27017"
  
  redis:
    image: redis
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    restart: always
    ports:
      - "5672:5672"     # AMQP protocol
      - "15672:15672"   # HTTP management UI