version: "3.8"

services: 
  mongodb:
    image: mongo
    container_name: app-mongodb
    restart: always
    ports:
      - "27018:27017"
  
  redis:
    image: redis
    container_name: app-redis
    restart: always
    ports:
      - "6379:6379"